export const domainErrorMessages = {
    auth: {
        emailVerificationIdCannotBeEmpty: 'Идентификатор подтверждения email не может быть пустым',
        emailVerificationTokenCannotBeEmpty: 'Токен подтверждения email не может быть пустым',
        emailVerificationAlreadyUsed: 'Токен подтверждения email уже использован',
        emailVerificationExpired: 'Срок действия токена подтверждения email истёк',
        emailVerificationNotFound: 'Токен подтверждения email не найден',
        emailVerificationEmailCannotBeEmpty: 'Email в запросе подтверждения не может быть пустым',
        invalidCredentials: 'Неверные учетные данные',
    },
    user: {
        alreadyBlocked: 'Пользователь уже заблокирован',
        notBlocked: 'Пользователь не заблокирован',
        idCannotBeEmpty: 'Идентификатор пользователя не может быть пустым',
        typeIsRequired: 'Тип пользователя обязателен',
        invalidEmailFormat: 'Неверный формат адреса электронной почты',
        usernameCannotBeEmpty: 'Имя пользователя не может быть пустым',
        passwordHashCannotBeEmpty: 'Хэш пароля не может быть пустым',
        subscriptionCountCannotBeNegative: 'Количество подписок не может быть отрицательным',
        cannotDecrementSubscriptionBelowZero: 'Нельзя уменьшить количество подписок ниже нуля',
        typeIdCannotBeEmpty: 'Идентификатор типа пользователя не может быть пустым',
        typeNameCannotBeEmpty: 'Название типа пользователя не может быть пустым',
        userAlreadyExists: 'Пользователь с такой почтой уже создан',
        passwordNotVerified: 'Неверный пароль',
        emailAlreadyVerified: 'Почта уже подтверждена',
        pendingEmailAlreadyRequested: 'Запрос на смену почты уже создан',
        pendingEmailNotFound: 'Нет ожидающего подтверждения email',
        pendingEmailMatchesCurrent: 'Новый email совпадает с текущим',
        pendingEmailMismatch: 'Подтверждаемый email не совпадает с ожидаемым',
        userEventIdCannotBeEmpty: 'Идентификатор подписки не может быть пустым',
        userEventNameCannotBeEmpty: 'Имя подписки не может быть пустым',
        userEventSubscriptionsCountCannotBeNegative: 'Количество подписчиков у подписки не может быть пустым',
    },
    comment: {
        textCannotBeEmpty: 'Текст комментария не может быть пустым',
        idCannotBeEmpty: 'Идентификатор комментария не может быть пустым',
        eventIdCannotBeEmpty: 'Идентификатор события комментария не может быть пустым',
        authorIsRequired: 'Автор комментария обязателен',
        cannotEditDeleted: 'Нельзя редактировать удалённый комментарий',
        alreadyDeleted: 'Комментарий уже удалён',
        userIdCannotBeEmpty: 'Идентификатор пользователя комментария не может быть пустым',
        usernameCannotBeEmpty: 'Имя пользователя комментария не может быть пустым',
    },
    event: {
        invalidDate: 'Некорректная дата события',
        idCannotBeEmpty: 'Идентификатор события не может быть пустым',
        organizerIsRequired: 'Организатор события обязателен',
        categoryIsRequired: 'Категория события обязательна',
        titleCannotBeEmpty: 'Название события не может быть пустым',
        descriptionCannotBeEmpty: 'Описание события не может быть пустым',
        locationCannotBeEmpty: 'Локация события не может быть пустой',
        userAlreadySubscribed: 'Пользователь уже подписан на событие',
        userNotSubscribed: 'Пользователь не подписан на событие',
        categoryNameCannotBeEmpty: 'Название категории не может быть пустым',
        categoryIdCannotBeEmpty: 'Идентификатор категории не может быть пустым',
        subscriberCountCannotBeNegative: 'Количество подписчиков не может быть отрицательным',
        commentCountCannotBeNegative: 'Количество комментариев не может быть отрицательным',
        cannotDecrementSubscriberBelowZero: 'Нельзя уменьшить количество подписчиков ниже нуля',
        cannotDecrementCommentBelowZero: 'Нельзя уменьшить количество комментариев ниже нуля',
        organizerIdCannotBeEmpty: 'Идентификатор организатора не может быть пустым',
        organizerUsernameCannotBeEmpty: 'Имя пользователя организатора не может быть пустым',
        organizerPersonalDataCannotBeEmpty: 'Персональные данные организатора не могут быть пустыми',
        eventAlreadyStarted: 'Нельзя подписаться на событие, которое уже началось',
        categoryInUse: 'Нельзя удалить категорию, к которой привязаны события',
        categoryAlreadyExists: 'Категория с таким названием уже существует',
        eventSubscriberIdCannotBeEmpty: 'Идентификатор подписчика не может быть пустым',
        eventSubscriberNameCannotBeEmpty: 'Имя подписчика не может быть пустым',
    },
    notification: {
        messageCannotBeEmpty: 'Сообщение уведомления не может быть пустым',
        idCannotBeEmpty: 'Идентификатор уведомления не может быть пустым',
        eventIdCannotBeEmpty: 'Идентификатор события уведомления не может быть пустым',
        userIsRequired: 'Пользователь уведомления обязателен',
        typeCannotBeEmpty: 'Тип уведомления не может быть пустым',
        alreadySent: 'Уведомление уже отправлено',
        userIdCannotBeEmpty: 'Идентификатор пользователя уведомления не может быть пустым',
        usernameCannotBeEmpty: 'Имя пользователя уведомления не может быть пустым',
    },
    common: {
        notFound: 'Данные не найдены',
        notRights: 'У вас недостаточно прав для данного действия',
    },
} as const;
