export const ERROR_MESSAGES = {
    api: {
        auth: {
            usernameRequired: 'Имя пользователя обязательно',
            usernameTooLong: 'Имя пользователя слишком длинное (максимум 100 символов)',
            emailInvalid: 'Неверный формат email',
            passwordRequired: 'Пароль обязателен',
            passwordMinLength: 'Пароль должен содержать минимум 8 символов',
            passwordUppercase: 'Пароль должен содержать хотя бы одну заглавную букву',
            passwordLowercase: 'Пароль должен содержать хотя бы одну строчную букву',
            passwordNumber: 'Пароль должен содержать хотя бы одну цифру',
            passwordSpecialChar: 'Пароль должен содержать хотя бы один специальный символ',
            refreshTokenRequired: 'Refresh token обязателен',
        },
        user: {
            usernameRequired: 'Имя пользователя обязательно',
            emailInvalid: 'Неверный формат email',
            passwordRequired: 'Пароль обязателен',
            oldPasswordRequired: 'Старый пароль обязателен',
            newPasswordMinLength: 'Новый пароль должен содержать минимум 8 символов',
        },
        event: {
            titleRequired: 'Название события обязательно',
            titleTooLong: 'Название события слишком длинное (максимум 200 символов)',
            descriptionRequired: 'Описание события обязательно',
            locationRequired: 'Местоположение обязательно',
            locationTooLong: 'Местоположение слишком длинное (максимум 200 символов)',
            dateInvalid: 'Неверный формат даты',
            latitudeOutOfRange: 'Широта должна быть в диапазоне от -90 до 90',
            longitudeOutOfRange: 'Долгота должна быть в диапазоне от -180 до 180',
            locationRequiresCoordinates: 'Если указано местоположение, необходимо указать широту и долготу',
            messageRequired: 'Сообщение обязательно',
            photoUrlInvalid: 'Неверный формат URL фотографии',
        },
        category: {
            nameRequired: 'Название категории обязательно',
            nameTooLong: 'Название категории слишком длинное (максимум 100 символов)',
        },
        comment: {
            textRequired: 'Текст комментария обязателен',
            textTooLong: 'Комментарий слишком длинный (максимум 1000 символов)',
        },
        userType: {
            nameRequired: 'Название типа пользователя обязательно',
            nameTooLong: 'Название типа пользователя слишком длинное (максимум 100 символов)',
        },
        geocoder: {
            locationRequired: 'Местоположение не может быть пустым',
        },
    },
    domain: {
        auth: {
            emailVerificationIdCannotBeEmpty: 'Идентификатор подтверждения email не может быть пустым',
            emailVerificationUserIdCannotBeEmpty: 'Идентификатор пользователя не может быть пустым',
            emailVerificationTokenCannotBeEmpty: 'Токен подтверждения email не может быть пустым',
            emailVerificationAlreadyUsed: 'Токен подтверждения email уже использован',
            emailVerificationExpired: 'Срок действия токена подтверждения email истёк',
            emailVerificationEmailCannotBeEmpty: 'Email в запросе подтверждения не может быть пустым',
            invalidTokenPayload: 'Неверные токены авторизации',
            inactiveToken: 'Срок действия авторизации истек',
            invalidEmailVerificationPurpose: 'Неверная цель подтверждения email',
        },
        user: {
            alreadyBlocked: 'Пользователь уже заблокирован',
            notBlocked: 'Пользователь не заблокирован',
            idCannotBeEmpty: 'Идентификатор пользователя не может быть пустым',
            typeIsRequired: 'Тип пользователя обязателен',
            invalidEmailFormat: 'Неверный формат адреса электронной почты',
            usernameCannotBeEmpty: 'Имя пользователя не может быть пустым',
            passwordHashCannotBeEmpty: 'Хэш пароля не может быть пустым',
            subscriptionCountCannotBeNegative: 'Количество подписок не может быть отрицательным',
            cannotDecrementSubscriptionBelowZero: 'Нельзя уменьшить количество подписок ниже нуля',
            typeIdCannotBeEmpty: 'Идентификатор типа пользователя не может быть пустым',
            typeNameCannotBeEmpty: 'Название типа пользователя не может быть пустым',
            passwordNotVerified: 'Неверный пароль',
            emailAlreadyVerified: 'Почта уже подтверждена',
            pendingEmailAlreadyRequested: 'Запрос на смену почты уже создан',
            pendingEmailNotFound: 'Нет ожидающего подтверждения email',
            pendingEmailMatchesCurrent: 'Новый email совпадает с текущим',
            pendingEmailMismatch: 'Подтверждаемый email не совпадает с ожидаемым',
            avatarUrlCannotBeEmpty: 'URL аватара не может быть пустым',
        },
        userType: {
            idCannotBeEmpty: 'Идентификатор типа пользователя не может быть пустым',
            nameCannotBeEmpty: 'Название типа пользователя не может быть пустым',
            alreadyExists: 'Тип пользователя с таким названием уже существует',
            inUse: 'Нельзя удалить тип пользователя, так как есть пользователи с этим типом',
            invalidRole: 'Неверная роль пользователя',
        },
        comment: {
            textCannotBeEmpty: 'Текст комментария не может быть пустым',
            idCannotBeEmpty: 'Идентификатор комментария не может быть пустым',
            eventIdCannotBeEmpty: 'Идентификатор события комментария не может быть пустым',
            authorIsRequired: 'Автор комментария обязателен',
            cannotEditDeleted: 'Нельзя редактировать удалённый комментарий',
            alreadyDeleted: 'Комментарий уже удалён',
            userIdCannotBeEmpty: 'Идентификатор пользователя комментария не может быть пустым',
            usernameCannotBeEmpty: 'Имя пользователя комментария не может быть пустым',
        },
        event: {
            invalidDate: 'Некорректная дата события',
            idCannotBeEmpty: 'Идентификатор события не может быть пустым',
            organizerIsRequired: 'Организатор события обязателен',
            categoryIsRequired: 'Категория события обязательна',
            titleCannotBeEmpty: 'Название события не может быть пустым',
            descriptionCannotBeEmpty: 'Описание события не может быть пустым',
            locationCannotBeEmpty: 'Локация события не может быть пустой',
            userAlreadySubscribed: 'Пользователь уже подписан на событие',
            categoryIdCannotBeEmpty: 'Идентификатор категории не может быть пустым',
            categoryNameCannotBeEmpty: 'Название категории не может быть пустым',
            subscriberCountCannotBeNegative: 'Количество подписчиков не может быть отрицательным',
            commentCountCannotBeNegative: 'Количество комментариев не может быть отрицательным',
            cannotDecrementSubscriberBelowZero: 'Нельзя уменьшить количество подписчиков ниже нуля',
            cannotDecrementCommentBelowZero: 'Нельзя уменьшить количество комментариев ниже нуля',
            organizerIdCannotBeEmpty: 'Идентификатор организатора не может быть пустым',
            organizerUsernameCannotBeEmpty: 'Имя пользователя организатора не может быть пустым',
            organizerPersonalDataCannotBeEmpty: 'Персональные данные организатора не могут быть пустыми',
            organizerAvatarCannotBeEmpty: 'Аватар огранизатора не может быть пустыми',
            eventAlreadyStarted: 'Нельзя подписаться на событие, которое уже началось',
            eventSubscriberIdCannotBeEmpty: 'Идентификатор подписчика не может быть пустым',
            eventSubscriberNameCannotBeEmpty: 'Имя подписчика не может быть пустым',
            galleryUrlCannotBeEmpty: 'URL фотографии галереи не может быть пустым',
            galleryMaxPhotosExceeded: 'Максимальное количество фотографий в галерее превышено',
            galleryPhotoNotFoundException: 'Фотография в галерее не найдена',
            invalidLatitude: 'Широта должна быть в диапазоне от -90 до 90',
            invalidLongitude: 'Долгота должна быть в диапазоне от -180 до 180',
        },
        notification: {
            messageCannotBeEmpty: 'Сообщение уведомления не может быть пустым',
            idCannotBeEmpty: 'Идентификатор уведомления не может быть пустым',
            eventIdCannotBeEmpty: 'Идентификатор события уведомления не может быть пустым',
            userIsRequired: 'Пользователь уведомления обязателен',
            typeCannotBeEmpty: 'Тип уведомления не может быть пустым',
            userIdCannotBeEmpty: 'Идентификатор пользователя уведомления не может быть пустым',
            invalidType: 'Неверный тип уведомления',
            usernameCannotBeEmpty: 'Имя пользователя уведомления не может быть пустым',
        },
    },
    application: {
        common: {
            invalidInput: 'Некорректный формат данных',
            routeNotFound: 'Маршрут не найден',
            unknownError: 'Неизвестная ошибка',
            accessDenied: 'У вас недостаточно прав для данного действия',
            notAuthenticated: 'Не авторизован',
        },
        user: {
            notFound: 'Пользователь не найден',
            alreadyExists: 'Пользователь с такой почтой уже существует',
            userTypeNotFound: 'Тип пользователя не найден',
            accessDenied: 'У вас недостаточно прав для данного действия',
            eventForUserNotFound: 'Событие для пользователя не найдено',
            emailVerificationForUserAlreadyRequested: 'Запрос на подтверждение email уже создан',
        },
        userType: {
            notFound: 'Тип пользователя не найден',
            alreadyExists: 'Тип пользователя с таким названием уже существует',
            inUse: 'Нельзя удалить тип пользователя, так как есть пользователи с этим типом',
        },
        category: {
            notFound: 'Категория не найдена',
            alreadyExists: 'Категория с таким названием уже существует',
            inUse: 'Нельзя удалить категорию, к которой привязаны события',
        },
        event: {
            notFound: 'Событие не найдено',
            alreadyStarted: 'Нельзя подписаться на событие, которое уже началось',
            userAlreadySubscribed: 'Пользователь уже подписан на событие',
            userNotSubscribed: 'Пользователь не подписан на событие',
            accessDenied: 'У вас недостаточно прав для данного действия',
            userForEventNotFound: 'Пользователь для события не найден',
            categoryForEventNotFound: 'Категория для события не найдена',
        },
        comment: {
            notFound: 'Комментарий не найден',
            cannotEditDeleted: 'Нельзя редактировать удалённый комментарий',
            accessDenied: 'У вас недостаточно прав для данного действия',
            userForCommentNotFound: 'Пользователь для комментария не найден',
            eventForCommentNotFound: 'Событие для комментария не найдено',
        },
        auth: {
            invalidCredentials: 'Неверные учетные данные',
            emailVerificationNotFound: 'Токен подтверждения email не найден',
            emailVerificationExpired: 'Срок действия токена подтверждения email истёк',
            emailVerificationAlreadyUsed: 'Токен подтверждения email уже использован',
            emailVerificationAlreadyRequested: 'Запрос на подтверждение email уже создан',
            userForAuthNotFound: 'Пользователь для аутентификации не найден',
        },
        notification: {
            notFound: 'Уведомление не найдено',
            eventForNotificationNotFound: 'Событие для уведомления не найдено',
        },
        file: {
            invalidFileType: 'Недопустимый тип файла',
            invalidFileExtension: 'Недопустимое расширение файла',
            fileSizeExceeded: 'Размер файла превышает максимально допустимый',
            imageWidthExceeded: 'Ширина изображения превышает максимально допустимую',
            imageHeightExceeded: 'Высота изображения превышает максимально допустимую',
            noFileUploaded: 'Файл не был загружен',
            fileProcessingError: 'Ошибка при обработке файла',
        },
        geocoder: {
            failed: 'Не удалось определить координаты. Попробуйте позже',
            notFound: 'Не удалось найти указанный адрес. Проверьте правильность написания',
            invalidResponse: 'Не удалось определить координаты. Попробуйте позже',
            configurationError: 'Сервис определения координат временно недоступен',
        },
        bot: {
            sendMessageFailed: 'Не удалось отправить уведомление. Попробуйте позже',
        },
        email: {
            sendFailed: 'Не удалось отправить письмо. Попробуйте позже',
        },
        fileStorage: {
            moveFailed: 'Не удалось переместить файл. Попробуйте позже',
            deleteFailed: 'Не удалось удалить файл. Попробуйте позже',
            fileNotFound: 'Файл не найден',
            accessDenied: 'Нет доступа к файлу',
            ioError: 'Ошибка ввода-вывода файловой системы',
        },
        token: {
            signFailed: 'Не удалось выполнить операцию. Попробуйте позже',
            verifyFailed: 'Не удалось выполнить операцию. Попробуйте позже',
            invalidToken: 'Сессия недействительна. Войдите снова',
            expiredToken: 'Сессия истекла. Войдите снова',
        },
        security: {
            csrfOriginRequired: 'Заголовок Origin или Referer обязателен для данного запроса',
            csrfInvalidOrigin: 'Недопустимый источник запроса',
            rateLimitExceeded: 'Слишком много попыток аутентификации, попробуйте снова через 15 минут',
        },
    },
} as const;
